#  https://nubcakes.net/index.php/2019/04/03/how-to-install-sonarr-radarr-and-jackett-with-docker-compose/
#  https://jellyfin.org/docs/general/administration/installing.html#container-images
#
# restart with:
#    docker-compose pull && docker-compose up -d
version: '3'
services:

 jellyfin:
  container_name: jellyfin
  restart: unless-stopped
  ports:
   - 8096:8096
  # network_mode: host
  user: 1000:1000
  volumes:
      - /home/dante/docker/stack-jellyfin/config/jellyfin:/config
      - /var/lib/docker/volumes/jellyfin_cache/_data:/cache
      - /var/lib/docker/volumes/downloads/_data:/media
  image: jellyfin/jellyfin

 radarr:
  container_name: radarr
  restart: unless-stopped
  ports:
   - 7878:7878
  volumes:
   - /home/dante/docker/stack-jellyfin/config/radarr:/config
   - /var/lib/docker/volumes/downloads/_data:/downloads
   - /var/lib/docker/volumes/synomovies/_data:/movies
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Europe/Rome
  image: linuxserver/radarr
  
 sonarr:
  container_name: sonarr
  restart: unless-stopped
  ports:
   - 8989:8989
  volumes:
   - /home/dante/docker/stack-jellyfin/config/sonarr:/config
   - /var/lib/docker/volumes/downloads/_data:/downloads
   - /var/lib/docker/volumes/downloads/_data:/tv
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Europe/Rome
  image: linuxserver/sonarr

 jackett:
  container_name: jackett
  restart: unless-stopped
  ports:
   - 9117:9117
  volumes:
   - /home/dante/docker/stack-jellyfin/config/jackett:/config
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Europe/Rome
  image: linuxserver/jackett
